# Generated by Django 4.2.7 on 2024-12-03 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f1",
                    models.CharField(
                        help_text="Enter a field (e.g. Dodge)",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Make must be greater than 1 character"
                            )
                        ],
                    ),
                ),
                (
                    "f2",
                    models.CharField(
                        help_text="Enter a field (e.g. Dodge)",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Make must be greater than 1 character"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
