# Generated by Django 4.2.7 on 2024-12-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fields",
        ),
    ]
