# Generated by Django 4.2.7 on 2024-12-11 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_notes_alter_project_repo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="notes",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "Notes must be greater than 10 characters"
                    )
                ],
            ),
        ),
    ]
